name: Update README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      run: python readme-update.py
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "mail@ledinhcuong.com"
        git config --global user.name "README-update"
        git add -A
        git commit -m "Updated content" || exit 0
        git push
